spring:
  profiles:
    active: local

server:
  port: 8081
---
spring:
  profiles: local
  redis:
    host: 127.0.0.1
    port: 6379

restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5

app:
  api:
    url: http://10.83.36.142:8082
  redirectUrl: http://10.83.36.91:3000
  returnUrl: http://localhost:3000

---

spring:
  profiles: dev

server:
  port: 8081

---

spring:
  profiles: production
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    root: info

restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5

app:
  api:
    url: http://106.10.37.166:8082
  payFront: http://106.10.37.166:9001
  returnUrl: http://106.10.37.166:9000
