spring:
  profiles:
    active: local
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8081

restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5

---
spring:
  profiles: local

url:
  return: localhost:8081/merchant/pay/complete
  pay:
    api: localhost:8082/
---
spring:
  profiles: dev

---

