spring:
  profiles:
    active: local

server:
  port: 8080

mybatis:
  type-aliases-package: com.example.myproject.mapper
  mapper-locations: mapper/*.xml

---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/offline_qr_payment?serverTimezone=Asia/Seoul
    username: root
    password: qnpfr1021

---

spring:
  profiles: dev

---

spring:
  profiles: production
